schema_version = "1.0.0"

id = "editorbar"
version = "0.4.1"
name = "EditorBar"
tagline = "Turn Outliner & Properties editors into a toggleable sidebar"
maintainer = "Blazing Fast Labs <james@jamesn.design>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

tags = ["User Interface"]

website = "https://github.com/JamesN-dev/blender-editorbar"
tracker = "https://github.com/JamesN-dev/blender-editorbar/issues"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.lock",
  "*.zip",
  "pyproject.toml",
  "pyrightconfig.json",
  "ruff.toml"
]
