# Exclude patterns
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  '.zed',
  "__pypackages__",
  "_build",
  "build",
  'images',
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "data",
  "docs",
  "logs",
  "migrations",
  "frontend",
]

# Basic configuration
line-length = 88
indent-width = 4
target-version = 'py312'

[lint]
# Core rule sets suitable for a small Blender add-on
select = ['E', 'W', 'F', 'UP', 'B', 'I', 'C4', 'SIM', 'RUF']
# Ignore line-length; let the formatter handle wrapping
ignore = ['E501']

# --fix behavior
fixable = ["ALL"]
unfixable = []

[format]
# Prefer single quotes in formatted code
quote-style = 'single'
indent-style = 'space'
skip-magic-trailing-comma = false
line-ending = 'auto'
